---
- name: Add Symas repo
  ansible.builtin.yum_repository:
    name: Symas OpenLDAP for Linux
    description: Symas yum repo
    file: sofl
    baseurl: https://repo.symas.com/repo/rpm/SOFL/rhel8/
    gpgcheck: yes
    gpgkey: https://repo.symas.com/repo/gpg/RPM-GPG-KEY-symas-com-signing-key

- name: Install openLDAP
  dnf:
    name: "{{ item }}"
    state: present
    enablerepo: sofl
    update_cache: yes
  with_items:
    - symas-openldap-servers
    - symas-openldap-clients
    - oddjob-mkhomedir