---
- name: Enterprise Linux 7
  include: EL-7.yml
  when:
    - ansible_os_family: == "RedHat"
    - ansible_distribution_major_version|int in [6,7]

- name: Enterprise Linux 8
  include: EL-8.yml
  when:
    - ansible_os_family: == "RedHat"
    - ansible_distribution_major_version|int in [8]

- name: Set SELinux ypbind
  ansible.posix.seboolean:
    name: allow_ypbind
    persistent: yes
    state: yes

- name: Set SELinux use_ldap
  ansible.posix.seboolean:
    name: authlogin_nsswitch_use_ldap
    persistent: yes
    state: yes

- name: Start slapd service
  service:
    name: slapd
    state: started
    enabled: yes

- name: Start oddjob service
  service:
    name: oddjobd
    state: started
    enabled: yes

- name: Register slappasswd
  command: slappasswd -s "{{ ldap_pw }}"
  register: ldap_hash

- name: Copy ldif
  template:
    src: "templates/{{ item.src }}"
    dest: "/tmp/{{ item.dest }}"
  with_items:
    - { src: 'db.ldif.j2', dest: 'db.ldif' }
    - { src: 'monitor.ldif.j2', dest: 'monitor.ldif' }

- name: ldapmodify
  shell: "ldapmodify -Y EXTERNAL -H ldapi:// -f /tmp/{{ item }}"
  with_items:
    - db.ldif
    - monitor.ldif

- name: copy database config
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: yes
    owner: ldap
    group: ldap

- name: setup database schemas
  shell: "ldapadd -Y EXTERNAL -H ldapi:// -f /etc/openldap/schema/{{ item }}"
  register: ldap_result
  failed_when: ldap_result.rc not in [0,80]
  changed_when: ldap_result.rc not in [0,80]
  with_items:
    - cosine.ldif
    - nis.ldif
    - inetorgperson.ldif

- name: Load ldap base entry
  community.general.ldap_entry:
    server_uri: "{{ server_uri }}"
    bind_dn: "{{ base_dn }}"
    bind_pw: "{{ ldap_pw }}"
    dn: "{{ base_dn }}"
    objectClass:
      - top
      - organization

- name: Load groups and users parent entry
  community.general.ldap_entry:
    server_uri: "{{ server_uri }}"
    bind_dn: "{{ base_dn }}"
    bind_pw: "{{ ldap_pw }}"
    dn: "ou={{ item }},{{ basedn }}"
    objectClass:
      - organizationalUnit
      - top
  with_items:
    - groups
    - people