---
- name: Enterprise Linux 7
  include: EL-7.yml
  when:
    - ansible_os_family: == "RedHat"
    - ansible_distribution_major_version|int in [6,7]

- name: Enterprise Linux 8
  include: EL-8.yml
  when:
    - ansible_os_family: == "RedHat"
    - ansible_distribution_major_version|int in [8]

- name: Set SELinux booleans
  ansible.posix.seboolean:
    name: {{ item }}
    persistent: yes
    state: yes
  with_items:
    - allow_ypbind
    - authlogin_nsswitch_use_ldap

- name: Start slapd service
  service:
    name: slapd
    state: started
    enabled: yes

- name: Start oddjob service
  service:
    name: oddjobd
    state: started
    enabled: yes

- name: Register slappasswd
  command: slappasswd -s "{{ slappasswd }}"
  register: ldap_password

- name: Copy ldif
  template:
    src: "templates/{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - { src: 'db.ldif.j2', dest: 'db.ldif' }
    - { src: 'monitor.ldif.j2', dest: 'monitor.ldif' }
    - { src: 'base.ldif.j2', dest: 'base.ldif' }

- name: ldapmodify
  shell: "ldapmodify -Y EXTERNAL -H ldapi:// -f /tmp/{{ item }}"
  with_items:
    - db.ldif
    - monitor.ldif
    - base.ldif

- name: copy database config
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: yes
    owner: ldap
    group: ldap

- name: setup database schemas
  shell: "ldapadd -Y EXTERNAL -H ldapi:// -f /etc/openldap/schema/{{ item }}"
  with_items:
    - cosine.ldif
    - nis.ldif
    - inetorgperson.ldif
  register: databases
  changed_when: databases

- name: Add base
  shell: ldapadd -x -W -D "cn=ldapadm,dc={{ domain }}" -f /tmp/base.ldif